### PR TITLE
feat(hat): Add tool to clear HAT eep contents

### PR DESCRIPTION
**Pull request by nbuchwitz**
For testing and other use cases it is necessary to clear the HAT eep contents. Add a CLI tool which zeros the eep.

### CODE REVIEW

**Comment by nbuchwitz** [comment]
CC @hjokunbus: Are there any other feature requests besides zeroing the HAT for production?

**Comment by hjokunbus** [comment]
> CC @hjokunbus: Are there any other feature requests besides zeroing the HAT for production?

None that I am aware of. Even zeroing HAT is not for production but testing and debugging.

**Comment by nbuchwitz** [comment]
Successfully tested:

```
# EEP before
pi@RevPi94337:~ $ sudo hexdump -C /sys/bus/i2c/devices/22-0050/eeprom 
00000000  52 2d 50 69 01 00 0a 00  fc 00 00 00 01 00 00 00  |R-Pi............|
00000010  3e 00 00 00 57 58 ba 17  68 f9 d0 80 f0 3c 51 3c  |>...WX..h....<Q<|
00000020  fb e7 0a e5 7f 01 0a 00  0b 1b 4b 55 4e 42 55 53  |..........KUNBUS|
00000030  20 47 6d 62 48 52 65 76  50 69 20 43 6f 6e 6e 65  | GmbHRevPi Conne|
00000040  63 74 20 34 20 57 4c 41  4e 20 31 36 2f 38 47 42  |ct 4 WLAN 16/8GB|
00000050  79 32 02 00 01 00 20 00  00 00 04 00 00 00 e0 e0  |y2.... .........|
00000060  e0 e0 e0 a0 e0 e0 e0 c0  e0 e0 e0 e0 e0 e0 e0 e0  |................|
00000070  e0 c0 e3 e3 e3 e3 e3 e3  8b 7a 03 00 02 00 10 00  |.........z......|
00000080  00 00 72 65 76 70 69 2d  63 6f 6e 6e 65 63 74 34  |..revpi-connect4|
00000090  f0 ea 04 00 03 00 03 00  00 00 31 84 14 04 00 04  |..........1.....|
000000a0  00 07 00 00 00 39 34 33  33 37 0a 98 04 00 05 00  |.....94337......|
000000b0  03 00 00 00 30 23 d4 04  00 06 00 0c 00 00 00 32  |....0#.........2|
000000c0  30 32 33 2d 30 35 2d 32  32 f7 6c 04 00 07 00 03  |023-05-22.l.....|
000000d0  00 00 00 30 00 14 04 00  08 00 13 00 00 00 63 38  |...0..........c8|
000000e0  3a 33 65 3a 61 37 3a 31  30 3a 37 66 3a 37 31 0e  |:3e:a7:10:7f:71.|
000000f0  9d 04 00 09 00 03 00 00  00 30 ef d4 ff ff ff ff  |.........0......|
00000100  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00008000


# Clear EEP
pi@RevPi94337:~/revpi-eol-provisioner $ sudo python3 -m revpi_provisioning.cli.clear_hat PR100383R00
Starting device provisioning for product 'PR100383R00'
Loading device configuration ... OK
Clear HAT EEPROM ... OK


# EEP after it was cleared
pi@RevPi94337:~/revpi-eol-provisioner $ sudo hexdump -C /sys/bus/i2c/devices/22-0050/eeprom 
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00008000

```

**Comment by iluminat23** [comment]
Do you want it zerod or cleared. Like it is new? This would be 0xff.

**Review by RamiGspo — COMMENTED** [review]
Maybe this commit can be also updated, for example:
`Add a CLI tool which zeros the eep.` => `Add a CLI tool to clean up the eep as new.`


https://github.com/RevolutionPi/revpi-eol-provisioner/pull/15/commits/270d1a9f679e776dd2527b0c72fca2a8fec4d2ac


After that, lgtm

**Review by RamiGspo — APPROVED** [review]

**Pull request merged**
